export const ALL_PROFILE_REQUEST = 'ALL_PROFILE_REQUEST'
export const ALL_PROFILE_SUCCESS = 'ALL_PROFILE_SUCCESS'
export const ALL_PROFILE_FAIL = 'ALL_PROFILE_FAIL'

export const PROFILE_DETAILS_REQUEST = 'PROFILE_DETAILS_REQUEST'
export const PROFILE_DETAILS_SUCCESS = 'PROFILE_DETAILS_SUCCESS'
export const PROFILE_DETAILS_FAIL = 'PROFILE_DETAILS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'